export const MOCK_BOOKS = [
  {
    id: 1,
    title: 'Đắc Nhân Tâm (How to Win Friends and Influence People)',
    author: 'Dale Carnegie',
    price: 120000,
    sale_price: 89000,
    cover_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600',
    local_jpg: '/images/dac-nhan-tam.jpg',
    description: 'Cuốn sách kinh điển về nghệ thuật ứng xử, giao tiếp và chinh phục lòng người hay nhất mọi thời đại.',
    stock: 25,
    category: 'Kỹ năng sống',
    rating: 4.9
  },
  {
    id: 2,
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    price: 450000,
    sale_price: 385000,
    cover_url: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=600',
    local_jpg: '/images/clean-code.jpg',
    description: 'Hướng dẫn thiết thực dành cho các lập trình viên để viết mã nguồn sạch, dễ bảo trì và mở rộng.',
    stock: 15,
    category: 'Công nghệ',
    rating: 4.8
  },
  {
    id: 3,
    title: 'Nhà Giả Kim (The Alchemist)',
    author: 'Paulo Coelho',
    price: 110000,
    sale_price: 79000,
    cover_url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600',
    local_jpg: '/images/nha-gia-kim.jpg',
    description: 'Hành trình theo đuổi vận mệnh của người chăn cừu Santiago đem lại những bài học sâu sắc về cuộc sống.',
    stock: 30,
    category: 'Văn học',
    rating: 4.9
  },
  {
    id: 4,
    title: 'Tư Duy Nhanh Và Chậm (Thinking, Fast and Slow)',
    author: 'Daniel Kahneman',
    price: 230000,
    sale_price: 175000,
    cover_url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600',
    local_jpg: '/images/tu-duy-nhanh-va-cham.jpg',
    description: 'Cuốn sách giải mã hai hệ thống tư duy chi phối cách con người suy nghĩ và đưa ra quyết định.',
    stock: 18,
    category: 'Kinh tế',
    rating: 4.7
  },
  {
    id: 5,
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    price: 580000,
    sale_price: 490000,
    cover_url: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=600',
    local_jpg: '/images/ddia.jpg',
    description: 'Cuốn kinh thánh về thiết kế hệ thống dữ liệu phân tán, xử lý tải cao và lưu trữ hiện đại.',
    stock: 10,
    category: 'Công nghệ',
    rating: 5.0
  },
  {
    id: 6,
    title: 'Cha Giàu Cha Nghèo (Rich Dad Poor Dad)',
    author: 'Robert T. Kiyosaki',
    price: 145000,
    sale_price: 105000,
    cover_url: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&q=80&w=600',
    local_jpg: '/images/cha-giau-cha-ngheo.jpg',
    description: 'Cuốn sách thay đổi tư duy tài chính cá nhân và kinh doanh bất động sản nổi tiếng toàn thế giới.',
    stock: 40,
    category: 'Kinh tế',
    rating: 4.8
  },
  {
    id: 7,
    title: 'Khéo Ăn Nói Sẽ Có Được Thiên Hạ',
    author: 'Trác Nhã',
    price: 115000,
    sale_price: 82000,
    cover_url: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&q=80&w=600',
    local_jpg: '/images/kheo-an-noi.jpg',
    description: 'Bí quyết giao tiếp thông minh, linh hoạt trong mọi tình huống giao tiếp thường ngày và công việc.',
    stock: 22,
    category: 'Kỹ năng sống',
    rating: 4.6
  },
  {
    id: 8,
    title: 'Hoàng Tử Bé (Le Petit Prince)',
    author: 'Antoine de Saint-Exupéry',
    price: 85000,
    sale_price: 62000,
    cover_url: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=600',
    local_jpg: '/images/hoang-tu-be.jpg',
    description: 'Tác phẩm văn học vượt thời gian dành cho cả trẻ em và người lớn về tình yêu và hành tinh.',
    stock: 35,
    category: 'Thiếu nhi',
    rating: 4.9
  }
];
